import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";
import { Input } from "@chakra-ui/react";
import ChatBubble from "../components/Chat/ChatBubble";
import styled from "@emotion/styled";

const Home: NextPage = () => {
  const [input, setInput] = useState<string>("");
  const [chats, setChats] = useState<string[]>([]);
  const [responses, setResponses] = useState<string[]>([]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Welcome to <a href="https://nextjs.org">DICE!</a>
        </h3>

        <ChatContainer>
          {chats.map((item) => {
            return <ChatBubble key={item} text={item} />;
          })}
          <form
            style={{ width: "100%" }}
            onSubmit={(e) => {
              e.preventDefault();
              setChats([...chats, input]);
              setResponses([...responses, input]);
              setInput("");
            }}>
            <ChatInput
              mt={3}
              value={input}
              onChange={(e) => setInput(e.currentTarget.value)}
            />
          </form>
        </ChatContainer>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;

const ChatContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 400px;
`;

const ChatInput = styled(Input)`
  position: fixed;
  bottom: 20px;
  width: 400px;
  border-radius: 16px;
  box-shadow: 4px 4px 15px rgba(0, 0, 0, 0.1);
  padding: 25px 18px;
  border: 1.4px solid black;

  &:hover {
    border: 1.4px solid black;
  }
  &:focus {
    outline: none;
  }
`;
